### ISSUE TITLE
SHA mismatch

### ISSUE THREAD

**Issue by michaeleiselsc** [chrismytton/gist-img#6]
$ brew install https://github.com/hecticjeff/gist-img/raw/master/extras/gist-img.rb
######################################################################## 100.0%
==> Downloading https://github.com/hecticjeff/gist-img/archive/v0.0.1.zip
==> Downloading from https://codeload.github.com/chrismytton/gist-img/zip/v0.0.1
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 168213f91284e740356a0df55ff6f6c203b128f95d5662124e1b53113c1625bf
Actual: 6d3b95fe70d5a03b3e3cd52d92fb2f9f1e2ba28cf105d20bbaefc017f43c46f3
Archive: /Library/Caches/Homebrew/gist-img-0.0.1.zip
To retry an incomplete download, remove the file above.

**Comment by chrismytton** [comment]
Thanks for reporting @michaeleiselsc, now fixed on master!
